---
title: "Retrieving stream measurement sites & data within an USGS Hydrological Region (HUC2)"
author: "brun@nceas.ucsb.edu"
date: "4/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning=FALSE}
library(tidyverse)
library(dataRetrieval)

output_path <- "/home/shares/camels/output/HUC01"
```


## Retrieving sites discharge

Here we are using the USGS hydrological Region `HUC01` as an example

```{r, eval=FALSE}
HUC2 <- "01"

sites <- whatNWISsites(huc = HUC2,
                       pCode <- "00060") # discharge sites

# Keeping only the HUC8 & Stream
sites <- sites %>% 
  filter(nchar(site_no) == 8 & site_tp_cd == "ST")


# Query for the daily discharge for all those sites
discharge <- "00060"
# Takes ~10hours!!!!
discharge_data <- readNWISdv(siteNumbers = sites$site_no,
                     parameterCd = discharge)

# Save the data as csv
write_csv(discharge_data, file.path(output_path,"huc01_daily_flow.csv"))
```

## Retrieving sites and data based on Chemistry

```{r, eval=FALSE}

# Read the priority codes of the chemical component we are interested in
my_codes <- read_csv("Parameter_Codes_Priority.csv")

# Query all the Stream sites
wq_sites <- whatWQPsites(huc = HUC2, 
                         pCode = my_codes$`5_digit_code`,
                         siteType="Stream")


# Check what is the data quantity available (seems to be bulk for all the codes)
wq_data_available <- whatWQPdata(siteid = wq_sites$MonitoringLocationIdentifier,
                                 pCode = my_codes$`5_digit_code`)

# Keep only sites with more than 10  measurements
data_sites_to_get <- wq_data_available %>% 
  filter(resultCount >= 10)

# Get the data
wq_data <- readWQPdata(siteNumbers = data_sites_to_get$MonitoringLocationIdentifier,
                        pCode = my_codes$`5_digit_code`)

# Remove the unwanted fields
# Read the list
chem_cols_drop <- read_csv("chem_fields_drop.csv") %>%
  separate(field_drop,c("number", "name"), sep = "-") %>%
  mutate(name = stringr::str_trim(name))

# Drop the fields
usgs_chem <-wq_data %>%
  select(-chem_cols_drop$name)

# Save the data as csv
write_csv(usgs_chem, file.path(output_path,"huc01_wq.csv"))

```

